name: Feature request
description: \U0001F680 Form to create a request for changes.
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        This form serves as a template to **create a request for changes**. It can be used, for example, to add a new section or functionality to the [FEGA-onboarding webspage](https://ega-archive.github.io/FEGA-onboarding/).
        Thank you for contributing to the Federated European Genome-phenome Archive (FEGA)!

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type(s)
      description: What type(s) of feature are you requesting? Select as many categories as you see fit from the dropdown menu.
      multiple: true
      options:
        - Content modification
        - Website appearance
        - GitHub repository
        - Other/unsure
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Please indicate the website URL or GitHub repository path where the requested change is located.
      placeholder: e.g. https://ega-archive.github.io/FEGA-onboarding/topics/maturity-model/
    validations:
      required: true 

  - type: textarea
    id: change-description
    attributes:
      label: Description of the change
      description: Please describe the change you are requesting. Make it as detailed as possible. 
      placeholder: e.g. I would like to request a new section be added at...
    validations:
      required: true
    
  - type: textarea
    id: change-reason
    attributes:
      label: Reason for the change
      description: Please explain why the change is being requested and what value it adds. 
      placeholder: e.g. Having a section about ... would ease the learning pace of...
    validations:
      required: true